version: '3'
services:
  mongo:
    image: mongo:latest
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27017" ]
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      retries: 30
    volumes:
      - "mongo_chat_data:/data/db"
      - "mongo_config_data:/data/configdb"
    networks:
      - spring-chat

networks:
  spring-chat:
    driver: bridge
volumes:
  mongo_chat_data:
  mongo_config_data: